### PR TITLE
Fix for stage 21 (error on Azure CLI)

### PR DESCRIPTION
**Pull request by krupers**
I found a fix for Azure CLI (usually at Azure Passes, when you can't create DLA credentials with Azure CLI 2.0. You can do it with PowerShell and here is a fix (described problem on https://github.com/MSFTImagine/computerscience/issues/76).

### CODE REVIEW

**Comment by shanamatthews** [comment]
Thanks @krupers ! I'll have to take a bit to check out what the original issue was and look at your change. Does this need an urgent fix (today?) or is it okay if I take a look tonight/tomorrow?

**Comment by krupers** [comment]
Yes, that is not a problem :) I just search at the fix on my lectures with students and I suggested them to switch to PowerShell and use this script, because they asked me for a problems with this WorkShop. Just decided to help us all with my little change that (maybe) can be used to solve some issues :) Thank you for quick reply!

**Comment by shanamatthews** [comment]
Awesome! I'll get a look in this week and hopefully get your change merged in.
Thank YOU for being a rockstar and sharing your fix!! 🥇 We really appreciate it.

**Comment by shanamatthews** [comment]
From issue report: 
Okay - it looks like there are 2 issues here:

This step was improperly updated for CLI 2.0 ("az config mode arm" isn't a real command anymore since CLI 2.0 only works with Resource Manager-based resources.)
There's some kind of bug in Cloud Shell with credential management... I'll see if I can get this routed to the right people :)


So, what this means is that I think the _right_ fix for this lab is to 
1. Correct the improper update
2. Point users to Azure CLI rather than Cloud Shell. 

I'll merge in your Powershell code snippet though, in case that's easier for people :)

**Pull request merged**
